spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:${PORT}/smart_wallet?createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
    resources:
      static-locations: file:./src/main/resources/static/
      cache-period: 0
users:
  default:
    role: USER
    account-state: true
subscription:
  default:
    type: DEFAULT
    status: ACTIVE
    period: MONTHLY
    price: 0.00
    renewalAllowed: true
wallet:
  default:
    status: ACTIVE
    balance: 20.00
    currency: EUR